FROM maven:3-adoptopenjdk-14 as Package

COPY ./src/main ./transfer_back/src/main
COPY pom.xml ./transfer_back

WORKDIR /transfer_back

RUN mvn clean package

FROM adoptopenjdk/openjdk14:jre-14.0.2_12-alpine

EXPOSE 5500

COPY --from=Package /transfer_back/target/diploma-0.0.1-SNAPSHOT.jar /app/transfer_rest.jar

WORKDIR /app

CMD ["java", "-jar", "transfer_rest.jar"]